### ISSUE TITLE
Rename this repo to perl6 ?

### ISSUE THREAD

**Issue by oyvindsk** [docker-exec/perl#1]
Hey

You might want to rename this repo to perl6 so the name can be used for Perl 5. 

Perl 5 is still the standard and will probably be so for a while. Perl == Perl 5.

**Comment by andystanton** [comment]
Thanks for the advice @oyvindsk - a few others have noted this too.

The plan is this:
1. Merge #2 resulting in this image being perl 5.
2. Create a separate image called perl6 from the old version.
3. Implement the change requested in docker-exec/dexec#11 allowing perl6 files with .pl extension to be executed with dexec by overriding the image it uses.
4. Associate .p6 files with the perl6 image as there are some references to this as an unofficial convention (https://www.google.co.uk/search?q=perl+.p6).

**Comment by oyvindsk** [comment]
Sounds like a good plan, +1
